# -*- coding: utf-8 -*-
"""VGG-NET_2024105526김다연.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAkqs8-tWC7uwMtQ57eeGu_Wvil-snAe
"""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms



device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

num_epochs = 80
learnig_rate = 0.001

transform = transforms.Compose([
    transforms.Pad(4),
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32),
    transforms.ToTensor()])

train_dataset = torchvision.datasets.CIFAR10(root = '../../data', train = True, download = True, transform = transform)
test_dataset = torchvision.datasets.CIFAR10(root = '../../data', train = False, download = True, transform = transforms.ToTensor())



train_loader = torch.utils.data.DataLoader(dataset = train_dataset, batch_size = 100, shuffle = True)
test_loader = torch.utils.data.DataLoader(dataset = test_dataset, batch_size = 100, shuffle = False)

class VGG(nn.Module):
  def __init__(self):
    super(VGG, self).__init__()
    self.maxpool = nn.MaxPool2d(4)
    self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1)
    self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1)
    self.relu = nn.ReLU(inplace=True)
    self.fc = nn.Linear(1568, 10)

  def forward(self, x):
    x = self.relu(self.conv1(x))
    x = self.relu(self.conv2(x))
    x = self.maxpool(x)
    x = x.view(x.size(0), -1)
    x = self.fc(x)

    return x



model = VGG().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learnig_rate)

def update_lr(optimizer, lr):
  for param_group in optimizer.param_groups:
    param_group['lr'] = lr

"""1. Training/Test를 for문 안에서 함께 수행하도록 코드를 변경하시오."""

total_step = len(train_loader)
curr_lr = learnig_rate

def train(epoch):
    model.train()

    for i, (images, labels) in enumerate(train_loader):

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch,num_epochs,i+1,total_step,loss.item()))

    if (epoch+1) % 20 == 0:
        curr_lr /= 3
        update_lr(optimizer, curr_lr)

def test():
    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    print('Test Accuracy: {} %'.format(100 * correct / total))

for epoch in range(1, 10):
  train(epoch)
  test()

"""2. 데이터 전처리로 정규화(normalization)를 수행하시오."""

norm_transform = transforms.Compose([transforms.ToTensor()])

norm_dataset = torchvision.datasets.CIFAR10(
    root='../../data',
    train=True,
    download=True,
    transform=norm_transform
)

norm_loader = torch.utils.data.DataLoader(
    norm_dataset,
    batch_size=100,
    shuffle=False
)

mean = 0.
std = 0.
total_images = 0

for images, _ in norm_loader:

    batch_samples = images.size(0)
    images = images.view(batch_samples,images.size(1),-1)

    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)
    total_images += batch_samples

mean /= total_images
std /= total_images

transform = transforms.Compose([
    transforms.Pad(4),
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32),
    transforms.ToTensor(),
    transforms.Normalize(mean.tolist(),
                         std.tolist())
])

test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean.tolist(),
                         std.tolist())
])

"""3. 아래 VGG모델을 구현하고 CIFAR-100 데이터를 학습하시오. 학습 결과
를 report 하시오
"""

train_dataset = torchvision.datasets.CIFAR100(root = '../../data', train = True, download = True, transform = transform)
test_dataset = torchvision.datasets.CIFAR100(root = '../../data', train = False, download = True, transform = transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset = train_dataset, batch_size = 100, shuffle = True)
test_loader = torch.utils.data.DataLoader(dataset = test_dataset, batch_size = 100, shuffle = False)

class VGG3(nn.Module):

    def __init__(self):
        super(VGG3, self).__init__()

        self.relu = nn.ReLU()


        self.block2_1 = nn.Conv2d(3, 64,kernel_size=3,padding=1)
        self.block2_2 = nn.Conv2d(64, 128,kernel_size=3,padding=1)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.block3_1 = nn.Conv2d(128, 512,kernel_size=3,padding=1)
        self.block3_2 = nn.Conv2d(512, 512,kernel_size=3,padding=1)
        self.block3_3 = nn.Conv2d(512, 512,kernel_size=3,padding=1)
        self.pool2 = nn.MaxPool2d(kernel_size=2,stride=2)

        self.fc1 = nn.Linear(512 * 8 * 8, 512)
        self.fc2 = nn.Linear(512,100)

    def forward(self, x):
        x = self.relu(self.block2_1(x))
        x = self.relu(self.block2_2(x))
        x = self.pool1(x)

        x = self.relu(self.block3_1(x))
        x = self.relu(self.block3_2(x))
        x = self.relu(self.block3_3(x))
        x = self.pool2(x)

        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x